platform :ios, '14.0'

flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'MyiOSApplication' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyiOSApplication
  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
    flutter_post_install(installer) if defined?(flutter_post_install)
end